export const tabs = document.querySelector('.tabs')
export const container = document.querySelector('.container')
export const modal = document.querySelector('.modal')
export const modalItems = document.querySelector('.modal-items')
export const modalSearch = document.querySelector('#modal-search')
